/**
 * List of icon files.
 * This file is autogenerated. Do not edit directly.
 * @file This file is saved as `icons_list.mjs`.
 */

/**
 * List of icon files.
 * @type {string[]}
 */
const list = [
  'lg32/standardAccount.svg',
  'rg24/systemActionABCKeypad.svg',
  'sm16/systemAdd.svg',
];

export default list;
